/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { ZKWarden } from "./contracts/ZKWarden.sol/ZKWarden";
export { ZKWarden__factory } from "./factories/contracts/ZKWarden.sol/ZKWarden__factory";
